name: Clang Format Check

on:
  pull_request:
    paths:
      - '**/*.c'
      - '**/*.h'
  push:
    paths:
      - '**/*.c'
      - '**/*.h'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Clang Format
        uses: matthewfeickert/clang-format-action@v2
        with:
          clang_format_version: 'latest'

      - name: Run clang-format
        run: |
          clang-format --dry-run --Werror $(find . -name '*.c' -or -name '*.h')
