name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: build
      run: make
    - name: run
      run: make run
    - name: format-check
      run: make format-check
    - name: run tests
      run: make test
